power <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
power2 <- power[power$Date %in% c("1/2/2007","2/2/2007") ,]
power2$Date <- as.Date(power2$Date, format = "%d/%m/%Y")
power2$Date <- with(power2, paste(Date, "T", Time, sep = " "))
power2$Date <- strptime(power2$Date, format = c("%Y-%m-%d T %H:%M:%S")) 
power2[,3:9] <- apply(power2[,3:9], 2, function(x) as.numeric(x))
png(file="plot4.png", width=480, height=480)
par(mfrow=c(2,2), mar=c(4,4,1,1), cex.axis=0.65, cex.lab=0.8)
with(power2, plot(Date, Global_active_power, type="l",xlab="", ylab="Global Active Power"))
with(power2, plot(Date, Voltage, type="l", xlab="datetime",ylab="Voltage"))
with(power2, plot(Date,Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
with(power2, points(Date,Sub_metering_2,type="l",col="red"))
with(power2, points(Date,Sub_metering_3,type="l",col="blue"))
with(power2, plot(Date, Global_reactive_power, type="l", xlab="datetime"))
dev.off()